#!/bin/bash

# Figma Asset Optimization Script
# Optimizes all exported assets from Figma

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ASSETS_DIR="$PROJECT_ROOT/figma-assets"

echo "🎨 Starting Figma asset optimization..."
echo "📁 Assets directory: $ASSETS_DIR"

# Check if assets directory exists
if [ ! -d "$ASSETS_DIR" ]; then
    echo "❌ Assets directory not found: $ASSETS_DIR"
    echo "💡 Run the extraction process first"
    exit 1
fi

# Check for required tools
check_tool() {
    if ! command -v "$1" &> /dev/null; then
        echo "⚠️  $1 not found. Install with: $2"
        return 1
    fi
    return 0
}

echo ""
echo "🔍 Checking required tools..."

MISSING_TOOLS=0

if ! check_tool "imageoptim" "brew install imageoptim-cli"; then
    MISSING_TOOLS=1
fi

if ! check_tool "cwebp" "brew install webp"; then
    MISSING_TOOLS=1
fi

if ! check_tool "svgo" "npm install -g svgo"; then
    MISSING_TOOLS=1
fi

if [ $MISSING_TOOLS -eq 1 ]; then
    echo ""
    echo "❌ Some required tools are missing. Please install them first."
    exit 1
fi

echo "✅ All tools available"
echo ""

# Function to optimize PNGs
optimize_pngs() {
    echo "📸 Optimizing PNG files..."
    find "$ASSETS_DIR" -name "*.png" -type f | while read -r file; do
        echo "  Optimizing: $(basename "$file")"
        imageoptim --quality 85-100 "$file" 2>/dev/null || true
    done
    echo "✅ PNG optimization complete"
}

# Function to optimize SVGs
optimize_svgs() {
    echo "🎨 Optimizing SVG files..."
    find "$ASSETS_DIR" -name "*.svg" -type f | while read -r file; do
        echo "  Optimizing: $(basename "$file")"
        svgo "$file" --multipass --quiet
    done
    echo "✅ SVG optimization complete"
}

# Function to create WebP versions
create_webp() {
    echo "🌐 Creating WebP versions..."
    find "$ASSETS_DIR" -name "*.png" -type f | while read -r file; do
        webp_file="${file%.png}.webp"
        if [ ! -f "$webp_file" ]; then
            echo "  Converting: $(basename "$file")"
            cwebp -q 85 "$file" -o "$webp_file" 2>/dev/null || true
        fi
    done
    echo "✅ WebP conversion complete"
}

# Function to create AVIF versions (if tool available)
create_avif() {
    if command -v avif &> /dev/null; then
        echo "🚀 Creating AVIF versions..."
        find "$ASSETS_DIR" -name "*.png" -type f | while read -r file; do
            avif_file="${file%.png}.avif"
            if [ ! -f "$avif_file" ]; then
                echo "  Converting: $(basename "$file")"
                avif --input="$file" --output="$avif_file" --quality=85 2>/dev/null || true
            fi
        done
        echo "✅ AVIF conversion complete"
    else
        echo "⏭️  Skipping AVIF (tool not installed: npm install -g avif)"
    fi
}

# Function to generate optimization report
generate_report() {
    echo ""
    echo "📊 Generating optimization report..."
    
    REPORT_FILE="$ASSETS_DIR/00-DOCUMENTATION/05-OPTIMIZATION-REPORT.md"
    
    cat > "$REPORT_FILE" << EOF
# PrayerMap Asset Optimization Report

**Date:** $(date +"%Y-%m-%d %H:%M:%S")
**Generated By:** optimize-figma-assets.sh

## Summary

### File Counts

\`\`\`
PNG Files: $(find "$ASSETS_DIR" -name "*.png" | wc -l | tr -d ' ')
SVG Files: $(find "$ASSETS_DIR" -name "*.svg" | wc -l | tr -d ' ')
WebP Files: $(find "$ASSETS_DIR" -name "*.webp" | wc -l | tr -d ' ')
AVIF Files: $(find "$ASSETS_DIR" -name "*.avif" | wc -l | tr -d ' ')
\`\`\`

### File Sizes

\`\`\`
Total PNG Size: $(du -sh "$ASSETS_DIR"/*.png 2>/dev/null | awk '{sum+=$1} END {print sum}' || echo "0")
Total SVG Size: $(du -sh "$ASSETS_DIR"/*.svg 2>/dev/null | awk '{sum+=$1} END {print sum}' || echo "0")
Total WebP Size: $(du -sh "$ASSETS_DIR"/*.webp 2>/dev/null | awk '{sum+=$1} END {print sum}' || echo "0")
\`\`\`

## Optimization Status

- [x] PNG optimization complete
- [x] SVG optimization complete
- [x] WebP conversion complete
- [$(command -v avif &> /dev/null && echo "x" || echo " ")] AVIF conversion complete

## Next Steps

1. Review optimized assets
2. Test in application
3. Update documentation
4. Commit to repository

EOF

    echo "✅ Report generated: $REPORT_FILE"
}

# Main execution
main() {
    optimize_pngs
    echo ""
    optimize_svgs
    echo ""
    create_webp
    echo ""
    create_avif
    echo ""
    generate_report
    echo ""
    echo "✨ Optimization complete!"
    echo "📊 Check the report: $ASSETS_DIR/00-DOCUMENTATION/05-OPTIMIZATION-REPORT.md"
}

main

